/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Wed Mar 19 21:26:00 2008"
#define BUILD_TIME (1205983560L)

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0xf01e0cc6UL
#define IGNORED_FEATURES 0xf0800000UL
#define VERSION_SANITY1 0x211b117eUL
#define VERSION_SANITY2 0xa48195c8UL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
 "Unix NetHack Version 3.4.3 - last build Wed Mar 19 21:26:00 2008."

